vdm_central_points = [center_of_respawn];
vdm_current_central_point = selectRandom vdm_central_points;

vdm_respawn_radius_max = 1500;
vdm_respawn_progressive_radius = true;
vdm_respawn_radius_min = 500;

vdm_vehicle_spawn_distance = 12;

vdm_arsenal_objects = [
arsenal_box_1,
arsenal_box_2,
arsenal_box_3,
arsenal_box_4,
arsenal_box_5,
arsenal_box_6,
arsenal_box_7,
arsenal_box_8,
arsenal_box_9,
arsenal_box_10,
arsenal_box_11,
arsenal_box_12,
arsenal_box_13,
arsenal_box_14,
arsenal_box_15,
arsenal_box_16,
arsenal_box_17,
arsenal_box_18,
arsenal_box_19,
arsenal_box_20,
arsenal_box_21,
arsenal_box_22,
arsenal_box_23,
arsenal_box_24,
arsenal_box_25,
arsenal_box_26,
arsenal_box_27,
arsenal_box_28,
arsenal_box_29,
arsenal_box_30,
arsenal_box_31,
arsenal_box_32,
arsenal_box_33,
arsenal_box_34,
arsenal_box_35,
arsenal_box_36,
arsenal_box_37,
arsenal_box_38,
arsenal_box_39,
arsenal_box_40,
arsenal_box_41,
arsenal_box_42,
arsenal_box_43,
arsenal_box_44,
arsenal_box_45,
arsenal_box_46,
arsenal_box_47,
arsenal_box_48,
arsenal_box_49,
arsenal_box_50,
arsenal_box_51,
arsenal_box_52,
arsenal_box_53,
arsenal_box_54,
arsenal_box_55,
arsenal_box_56,
arsenal_box_57,
arsenal_box_58,
arsenal_box_59,
arsenal_box_60
];